### PR TITLE
chore(semver): add config to disable GitHub comments on releases

### PR DESCRIPTION
**Pull request by tomudding**
# Description

Similar to what has been done to the SudoSOS repositories, disable commenting on issues and PRs that are included in a new release.

This way, we do not hit any of GH's (secret) rate limits, and it prevents unnecessary spam.

## Types of changes

- CI/CD _(Changes to the CI/CD configuration)_

### CODE REVIEW

**Comment by tomudding** [comment]
Why is `aurora-core` still using `master` as its default branch?

**Comment by Gijsdeman** [comment]
Reasons (@Yoronex never changed his local default settings, I think). Forgot to add the `.releaserc` for all repositories, will merge for the other two PRs and leave this one for until we have switched to `main`.

Outside of the scope of this PR, but I think we should add `.releaserc` to a shared configs repository (possibly a rebrand of `eslint-configs`, https://github.com/fisker/shared-configs). This way, we can make sure this is always synced across all repositories.

**Comment by tomudding** [comment]
> Reasons (@Yoronex never changed his local default settings, I think). Forgot to add the .releaserc for all repositories, will merge for the other two PRs and leave this one for until we have switched to main.

👍 

> Outside of the scope of this PR, but I think we should add .releaserc to a shared configs repository (possibly a rebrand of eslint-configs, https://github.com/fisker/shared-configs). This way, we can make sure this is always synced across all repositories.

I was thinking about this but did not have a specific solution in mind when creating these three PRs. I do agree that we should make sane defaults in `GEWIS/actions`.

> Edit @tomudding what is the goal of @semantic-release/git? I do not think we actually use this and their own documentation states that it is adviced to not make separate commits for releases (https://github.com/semantic-release/git).

I did a good ol' copy/paste from SudoSOS, but the idea is that it can automatically update `package.json` with the new version (effectively creating a commit for that).

**Comment by Gijsdeman** [comment]
I am not sure if that automatic commit for is actually working (I was unable to find any of those chore-releases in SudoSOS repository). Either way, it does not break anything and for consistency I will keep it in there for now.

**Comment by JustSamuel** [comment]
We do not use the automagical updating the package.json in sudosos.

**Comment by tomudding** [comment]
> I am not sure if that automatic commit for is actually working (I was unable to find any of those chore-releases in SudoSOS repository). Either way, it does not break anything and for consistency I will keep it in there for now.

I was about to say the same that I had not actually seen it in action. Perhaps it has something to do with the `develop` -> `main` updates that SudoSOS uses for release or perhaps it is something else. We will figure it out soon enough if it breaks something.

**Comment by tomudding** [comment]
> We do not use the automagical updating the package.json in sudosos.

Yet is is in the config, so please enlighten us how you make that not work?

**Comment by JustSamuel** [comment]
First of all, [you should not push commits as a result of a release](https://semantic-release.gitbook.io/semantic-release/support/faq#making-commits-during-the-release-process-adds-significant-complexity).

I think the reason why it does not work is also stated there: 
> Branch protection configuration must account for allowing the release user account to bypass restrictions enforced for human contributors, which might require elevating the access level of the release user beyond what would otherwise be desired/considered secure.

And since you cannot directly push to main nor develop, no extra commit is created.

It is not uncommon to do this manually instead (see https://github.com/michalchudziak/react-native-geolocation)

**Comment by Gijsdeman** [comment]
Actually, the config exists for both `core` and `backoffice`, but was missing for `client`. 
Instead of `.releaserc.json`, it is named [release.config.mjs](https://github.com/GEWIS/aurora-core/blob/e4e13b63682b7e3d7881d94a9e4511622835b6aa/release.config.mjs).

Oops

**Comment by tomudding** [comment]
> Actually, the config exists for both `core` and `backoffice`, but was missing for `client`. Instead of `.releaserc.json`, it is named [release.config.mjs](https://github.com/GEWIS/aurora-core/blob/e4e13b63682b7e3d7881d94a9e4511622835b6aa/release.config.mjs).
> 
> Oops

I apologise for not seeing this. Just goes to show that it is indeed a good idea to arrange this centrally with the actual workflow!

**Pull request closed without merging**
